version: '2'

services:
  app:
    image: 'expense-tracker:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/snapp?currentSchema=pay
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=test1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    networks:
      - snapp_pay_network

  db:
    image: 'postgres:14.4'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=snapp
    networks:
      - snapp_pay_network

networks:
  snapp_pay_network:
    driver: bridge